In [1]:
import torch

In [3]:
print(torch.__version__)

2.11.0+cpu


In [5]:
#Chechong its running in gpu or cpu
if torch.cuda.is_available():
  print("GPU is Availabe")
else:
 print("GPU is not available")

GPU is not available


**Creating Tensor**

In [10]:
#using empty
a = torch.empty(2,3)    #the values in output are random its only show that memory holds the following numbers

In [11]:
#check type
type(a)

torch.Tensor

In [12]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
#random
torch.rand(2,3)

tensor([[0.7262, 0.1689, 0.5260],
        [0.0541, 0.2970, 0.5581]])

In [19]:
#if i want to get some random numbers again and again then ill used seeds function
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [21]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
#other ways
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [25]:
#using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [26]:
#using eye ----> for identity matrix
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [27]:
#using full
torch.full([2,2],5) #----> matrix of order 2x2 and every element is 5

tensor([[5, 5],
        [5, 5]])

**Tensor Shape**

In [29]:
b = torch.tensor([[1,2,3],[4,5,6]])

In [31]:
#shape
b.shape

torch.Size([2, 3])

In [36]:
c = torch.tensor([[7,8,9],[3,4,5]])

In [37]:
torch.empty_like(c)

tensor([[134619029484656, 134617979256944,        11653544],
        [134619053424928, 134617677838256, 134617677838304]])

In [39]:
torch.zeros_like(c)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [40]:
torch.ones_like(c)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [46]:
torch.rand_like(c, dtype=torch.float64)
#----> this will generate an error because of c type is integer and random is always generate float type values
#to get random values using this we ust have to change the type of c to float datatype

tensor([[0.7911, 0.4274, 0.4460],
        [0.5522, 0.9559, 0.9405]], dtype=torch.float64)

Tansor **Datatypes**

In [48]:
#finding datatype
c.dtype

torch.int64

In [49]:
#Assingg data type
c.to(torch.float64)

tensor([[7., 8., 9.],
        [3., 4., 5.]], dtype=torch.float64)

#mathematical operations

In [54]:
#scalar operation
# addition
c + 2
# substraction
c - 2
# multiplication
c * 3
# division
c / 3
# int division
(c * 100)//3
# mod
((c * 100)//3)%2
# power
c**2

tensor([[49, 64, 81],
        [ 9, 16, 25]])

Element wise operation

In [56]:
d = torch.tensor([[7,8,9],[3,4,5]])
e = torch.tensor([[1,2,3],[4,5,6]])

In [57]:
# add
d+e
# sub
d-e
# multiply
d*e
# division
d/e
# power
d**e
# mod
d%e

tensor([[0, 0, 0],
        [3, 4, 5]])

In [59]:
f = torch.tensor([-1,2,-4,6])

In [60]:
#absolute
torch.abs(f)

tensor([1, 2, 4, 6])

In [61]:
#negitive
torch.negative(f)

tensor([ 1, -2,  4, -6])

In [63]:
g = torch.tensor([-1.5,2.0,-4.6,6.1])

In [65]:
#round
torch.round(g)

tensor([-2.,  2., -5.,  6.])

In [66]:
#ciel
torch.ceil(g)

tensor([-1.,  2., -4.,  7.])

In [67]:
#floor
torch.floor(g)

tensor([-2.,  2., -5.,  6.])

In [68]:
#clamp ----> to keep elements between two number means min and max
torch.clamp(g, min=1,max=4)

tensor([1., 2., 1., 4.])

Reduction operation

In [73]:
j = torch.randint(size=(2,3),low=1, high=10, dtype=torch.float32)
j

tensor([[7., 4., 9.],
        [3., 7., 6.]])

In [74]:
# sum
torch.sum(j)
# sum along columns
torch.sum(j, dim=0)
# sum along rows
torch.sum(j, dim=1)

tensor([20., 16.])

In [75]:
#mean
torch.mean(j)
# mean along columns
torch.mean(j, dim=0)
# mean along rows
torch.mean(j, dim=1)

tensor([6.6667, 5.3333])

In [76]:
#median, min, max, product, Sd,vairance
torch.median(j)
torch.min(j)
torch.max(j)
torch.prod(j)
torch.std(j)
torch.var(j)

tensor(4.8000)

In [77]:
#argmax----> finding index number of largest value
torch.argmax(j)
#argmin--->finding minimum number index
torch.argmin(j)

tensor(3)

Matrix operation

In [78]:
m= torch.randint(size=(2,3), low=0, high=10)
n = torch.randint(size=(3,2), low=0, high=10)

In [80]:
# matrix multiplcation
torch.matmul(m,n)

tensor([[121, 180],
        [109, 162]])

In [81]:
#transpose for a matrix like m
m

tensor([[5, 9, 9],
        [7, 5, 9]])

In [82]:
torch.transpose(m,0,1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [87]:
x = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

x

tensor([[4., 0., 8.],
        [4., 7., 2.],
        [3., 8., 5.]])

In [84]:
#determinant
torch.det(x)

tensor(-120.)

In [85]:
torch.inverse(x)

tensor([[ 4.1667e-02, -3.3333e-01,  3.4167e-01],
        [-4.1667e-02,  3.3333e-01, -1.4167e-01],
        [ 1.2500e-01, -6.9539e-09, -1.7500e-01]])

In [88]:
#copying tensor
#s = m  #(its good but)     -------> #here is a mistake which is s is only a indecator to the address of m , if we make change in
# m it also occurs in s - thats not pair. so we will use clone function

In [94]:
s = m.clone()

In [95]:
s

tensor([[5, 9, 9],
        [7, 5, 9]])

In [98]:
id(s) #------> id means address of s

134617626059200

In [99]:
id(m) #------> id means address of m

134617626196912

Inplace operation

In [100]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
#if we add m and n the third tensor will created and accupy space in memory, to save space we can stor
#we can store answer in m .

In [102]:
m.add_(n)

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [105]:
#reshaping
v = torch.ones(4,4)

In [106]:
v

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [107]:
#reshape methods
v.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [108]:
# flatten method ----> converting into one dimension
v.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [112]:
#squeezing
w = torch.rand(1,20)
w.squeeze(0).shape

torch.Size([20])

In [114]:
#unsqueez
q = torch.rand(226,226,3)
q.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])